/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDashboardGroup: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardPanel: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UForm: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UInput: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./../node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    UMain: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageHeader: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    UTable: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTooltip: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UColorModeButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
  const UContainer: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UDashboardGroup: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
  const UDashboardPanel: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
  const UDashboardSidebar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
  const UForm: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
  const UFormField: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UHeader: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
  const UInput: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const ULink: typeof import('./../node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
  const UMain: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
  const UNavigationMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  const UPage: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
  const UPageHeader: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
  const UTable: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  const UTooltip: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
}